version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
  optimization:
    build:
      context: .
      dockerfile: app.dockerfile
  rendering:
    build:
      context: .
      dockerfile: app.dockerfile
