version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: deployment/gateway.dockerfile
  frontend:
    build:
      context: ./
      dockerfile: deployment/frontend.dockerfile
  optimization:
    build:
      context: ./
      dockerfile: deployment/app.dockerfile
  rendering:
    build:
      context: ./
      dockerfile: deployment/app.dockerfile
