version: "3.8"
services:
  nginx:
    build:
      context: ./
      dockerfile: deployment/nginx.dockerfile
  optimization:
    build:
      context: ./
      dockerfile: deployment/app.dockerfile
  rendering:
    build:
      context: ./
      dockerfile: deployment/app.dockerfile
