import logging

from mcd_demo.app_config._config_utils import get_config, STRING_PARSER, INTEGER_PARSER, BOOLEAN_PARSER

LOGGING_LEVEL = get_config("APP_LOGGING_LEVEL", logging.INFO, STRING_PARSER)

OPTIMIZER_GENERATIONS = get_config("OPTIMIZER_GENERATIONS", 55, INTEGER_PARSER)
OPTIMIZER_POPULATION = get_config("OPTIMIZER_POPULATION", 85, INTEGER_PARSER)
SAMPLE_CLIPS_SUBSET = get_config("SAMPLE_CLIPS_SUBSET", True, BOOLEAN_PARSER)

RENDERER_POOL_SIZE = get_config("RENDERER_POOL_SIZE", 1, INTEGER_PARSER)
RENDERER_TIMEOUT = get_config("RENDERER_TIMEOUT", 25, INTEGER_PARSER)
RENDERER_TIMEOUT_GRANULARITY = get_config("RENDERER_TIMEOUT_GRANULARITY", 1, INTEGER_PARSER)
