version: "3.8"
services:
  nginx:
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    image: mcd-demo_nginx
    ports:
      - "443:443"
  optimization:
    hostname: optimization-app
    entrypoint: sh ./run_optimization_service.sh
    environment:
      - APP_HOSTNAME=optimization-app
      - APP_WORKERS=2
      - APP_ROOT_DIR=backend/src/
      - APP_PORT=8080
      - APP_THREADS=3
      - RENDERER_POOL_SIZE=0
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 750M
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: curl --fail optimization-app:8080/api/v1/health || exit 1
      interval: 10s
    image: mcd-demo_optimization
  rendering:
    hostname: rendering-app
    entrypoint: sh ./run_rendering_service.sh
    environment:
      - APP_HOSTNAME=rendering-app
      - APP_WORKERS=1
      - APP_THREADS=3
      - APP_ROOT_DIR=backend/src/
      - APP_PORT=8080
      - RENDERER_POOL_SIZE=1
      - RENDERER_TIMEOUT_GRANULARITY=1
      - RENDERER_TIMEOUT=15
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 750M
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: curl --fail rendering-app:8080/api/v1/health || exit 1
      interval: 10s
    image: mcd-demo_rendering
