version: "3.8"
services:
  gateway:
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    image: jyguru/mcd-demo-gateway:2024.jul.17
    volumes:
      - ../nginx/secrets:/secrets/
    ports:
      - "9090:80"
  frontend:
    hostname: frontend
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    image: jyguru/mcd-demo-frontend:2024.aug.22
    ports:
      - "5000:80"
  optimization:
    hostname: optimization-app
    entrypoint: sh ./run_optimization_service.sh
    environment:
      - APP_HOSTNAME=optimization-app
      - APP_WORKERS=1
      - APP_ROOT_DIR=backend/src/mcd_demo/
      - APP_PORT=8080
      - APP_THREADS=3
      - RENDERER_POOL_SIZE=0
      - SAMPLE_CLIPS_SUBSET="False"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: curl --fail optimization-app:8080/api/v1/health || exit 1
      interval: 10s
    image: jyguru/mcd-demo-backend:2024.aug.22
  rendering:
    hostname: rendering-app
    entrypoint: sh ./run_rendering_service.sh
    environment:
      - APP_HOSTNAME=rendering-app
      - APP_WORKERS=1
      - APP_THREADS=3
      - APP_ROOT_DIR=backend/src/mcd_demo/
      - APP_PORT=8080
      - RENDERER_POOL_SIZE=1
      - RENDERER_TIMEOUT_GRANULARITY=1
      - RENDERER_TIMEOUT=15
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: curl --fail rendering-app:8080/api/v1/health || exit 1
      interval: 10s
    image: jyguru/mcd-demo-backend:2024.aug.22
