import os

RENDERER_POOL_SIZE = int(os.getenv("RENDERER_POOL_SIZE", 3))
RENDERER_TIMEOUT = int(os.getenv("RENDERER_TIMEOUT", 25))
RENDERER_TIMEOUT_GRANULARITY = int(os.getenv("RENDERER_TIMEOUT_GRANULARITY", 1))
