name: Run tests

on:
  push:
    branches: [ pipeline-test ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Prepare virtual display
        run: Xvfb :99 -screen 0 800x600x8
      - name: export display variable
        run: export DISPLAY=:99
      - name: check display variable
        run: echo $DISPLAY
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt;
      - name: Install backend
        run: cd backend && pip install .;
      - name: run tests
        run: python -m unittest discover -s backend/test -t ./backend/test -v;
